#!/bin/sh

printf "Running preinst script\n"



#check if group exist and add it if not
if ! getent group ${debian.group} >/dev/null; then
    addgroup --system ${debian.group} >/dev/null
fi

#check if user exist and add it if not
if ! getent passwd ${debian.user} /dev/null; then
    adduser --system --disabled-login --ingroup ${debian.group} --shell /bin/false ${debian.user} >/dev/null
fi



mkdir -p ${debian.target.dir}/${project.artifactId}/libs
chown -R ${debian.user}.${debian.group} ${debian.target.dir}

mkdir -p ${logfiles.destination}
chown -R ${debian.user}.${debian.group} ${logfiles.destination}
